### ISSUE TITLE
Getting "Exception: Missing or incorrect metadata for Tower version."

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/awx-container#29]
Hitting a loop of the following error in the awx_web container:

```
awx_web_1    | 2018-02-06 23:21:58,766 INFO spawned: 'daphne' with pid 189
awx_web_1    | 2018-02-06 23:21:59,753 ERROR    Missing or incorrect metadata for Tower version.  Ensure Tower was installed using the setup playbook.
awx_web_1    | Traceback (most recent call last):
awx_web_1    |   File "/var/lib/awx/venv/awx/bin/daphne", line 11, in <module>
awx_web_1    |     sys.exit(CommandLineInterface.entrypoint())
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 144, in entrypoint
awx_web_1    |     cls().run(sys.argv[1:])
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 174, in run
awx_web_1    |     channel_layer = importlib.import_module(module_path)
awx_web_1    |   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
awx_web_1    |     __import__(name)
awx_web_1    |   File "/usr/lib/python2.7/site-packages/awx/asgi.py", line 31, in <module>
awx_web_1    |     raise Exception("Missing or incorrect metadata for Tower version.  Ensure Tower was installed using the setup playbook.")
awx_web_1    | Exception: Missing or incorrect metadata for Tower version.  Ensure Tower was installed using the setup playbook.
awx_web_1    | 2018-02-06 23:21:59,810 INFO success: daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
awx_web_1    | 2018-02-06 23:21:59,813 INFO exited: daphne (exit status 1; not expected)
```

Likely related to:

* https://github.com/geerlingguy/awx-container/issues/28
* https://github.com/ansible/awx/issues/1120

**Comment by geerlingguy** [comment]
Code in question: https://github.com/ansible/awx/blob/bfea00f6dc6af0fb01057ce38e9d0337e6c589aa/awx/wsgi.py#L22-L30

Looks like:

```python
        fd = open("/var/lib/awx/.tower_version", "r")
        if fd.read().strip() != tower_version:
            raise Exception()
```

So looking for a file that's apparently empty or not created in the path `/var/lib/awx/.tower_version`.

**Comment by geerlingguy** [comment]
...and that file should be created by this Dockerfile template: https://github.com/ansible/awx/blob/6163cc6b5c3a3c8f5bd173d121cafd15c5b75b17/installer/image_build/templates/Dockerfile.j2#L48

**Comment by geerlingguy** [comment]
Looking in my latest container version:

```
# cat /var/lib/awx/.tower_version 
1.0.3.55
```

I think I can just move the 'backup version string' task up one, so both templates (task and web) have it... will try that next.

**Comment by geerlingguy** [comment]
Now hitting: https://github.com/ansible/awx/issues/1148

**Comment by geerlingguy** [comment]
Grabbing the version from the filename (e.g. `awx-1.0.3.14.tar.gz`):

```yaml
- name: Set awx sdist filename and awx version.
  set_fact:
    awx_sdist_file: "{{ sdist_file.stdout_lines.0 }}"
    awx_version: "{{ sdist_file.stdout_lines.0 | regex_replace('^awx-(.*).tar.gz$', '\\1') }}"
```

**Comment by geerlingguy** [comment]
Back to a happy state after pulling latest devel! I'll be pushing up the new images.
