### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by rossedman** [geerlingguy/awx-container#3]
This may be an error with AWX itself, but when I run from docker-compose I receive this error when trying to login:

```
awx_web_1    | 2017-09-08 20:09:15,047 ERROR    django.request Internal Server Error: /api/v2/auth/
awx_web_1    | Traceback (most recent call last):
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
awx_web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
awx_web_1    |     return func(*args, **kwargs)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
awx_web_1    |     return view_func(*args, **kwargs)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
awx_web_1    |     return self.dispatch(request, *args, **kwargs)
awx_web_1    |   File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 246, in dispatch
awx_web_1    |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
awx_web_1    |     request = self.initialize_request(request, *args, **kwargs)
awx_web_1    |   File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 107, in initialize_request
awx_web_1    |     settings.PROXY_IP_WHITELIST,
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
awx_web_1    |     return getattr(self._wrapped, name)
awx_web_1    |   File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 386, in __getattr__
awx_web_1    |     value = self._get_local(name)
awx_web_1    |   File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
awx_web_1    |     self.gen.throw(type, value, traceback)
awx_web_1    |   File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 64, in _log_database_error
awx_web_1    |     if get_tower_migration_version() < '310':
awx_web_1    |   File "/usr/lib/python2.7/site-packages/awx/main/utils/db.py", line 13, in get_tower_migration_version
awx_web_1    |     loader = MigrationLoader(connection, ignore_no_migrations=True)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
awx_web_1    |     self.build_graph()
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
awx_web_1    |     self.applied_migrations = recorder.applied_migrations()
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
awx_web_1    |     self.ensure_schema()
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
awx_web_1    |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 58, in table_names
awx_web_1    |     return get_names(cursor)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 53, in get_names
awx_web_1    |     return sorted(ti.name for ti in self.get_table_list(cursor)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/introspection.py", line 53, in get_table_list
awx_web_1    |     AND pg_catalog.pg_table_is_visible(c.oid)""")
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
awx_web_1    |     return self.cursor.execute(sql, params)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
awx_web_1    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
awx_web_1    |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
awx_web_1    |     return self.cursor.execute(sql)
awx_web_1    | InternalError: current transaction is aborted, commands ignored until end of transaction block
```

Not sure where this is coming from. I noticed in the config for AWX port is set to 80 but it is actually serving on port 8052 and then being mapped to 80 with compose. Is this correct or related?

I'm also seeing this quite a bit in the database migrations

```
ERROR:  relation "conf_setting" does not exist at character 158
```

Thanks

**Comment by rossedman** [comment]
Closing, didn't let migrations run long enough. 👍
